services:
  app:
    build: .
    container_name: app
    ports:
      - '3000:3000'
    volumes:
      - .:/app # Synchronise ton code en temps réel (Hot Reload)
      - /app/node_modules # Isole les modules du conteneur
      - /app/.next # Isole le build du conteneur
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    depends_on:
      - db
      - mailpit

  db:
    image: postgres:15-alpine
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: always
    ports:
      - '8025:8025' # Interface Web
      - '1025:1025' # Port SMTP interne
    environment:
      MP_MAX_MESSAGES: 5000
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  postgres_data:
